/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_status2d.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "focusmaster.c"
#include "fullscreen.c"
#include "movestack.c"
#include "nametag.c"
#include "pertag.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_fibonacci.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

