# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ACA16E
background         #000102
cursor             #66644B

active_tab_foreground     #000102
active_tab_background     #ACA16E
inactive_tab_foreground   #ACA16E
inactive_tab_background   #000102

active_border_color   #ACA16E
inactive_border_color #000102
bell_border_color     #4A4F51

color0      #010102
color1		#4A4F51
color2		#4D504B
color3		#4B5545
color4		#555846
color5		#525959
color6		#6A6345
color7		#908656
color8		#655B30
color9		#4A4F51
color10		#4D504B
color11		#4B5545
color12		#555846
color13		#525959
color14		#6A6345
color15		#BFBAA2