# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #9E9EA0
background         #010102
cursor             #616266

active_tab_foreground     #010102
active_tab_background     #9E9EA0
inactive_tab_foreground   #9E9EA0
inactive_tab_background   #010102

active_border_color   #9E9EA0
inactive_border_color #010102
bell_border_color     #48474A

color0      #010102
color1		#48474A
color2		#4C494C
color3		#535359
color4		#59565B
color5		#56585C
color6		#606061
color7		#828285
color8		#59595B
color9		#48474A
color10		#4C494C
color11		#535359
color12		#59565B
color13		#56585C
color14		#606061
color15		#B8B8B9