# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #87A9D7
background         #010103
cursor             #6E6497

active_tab_foreground     #010103
active_tab_background     #87A9D7
inactive_tab_foreground   #87A9D7
inactive_tab_background   #010103

active_border_color   #87A9D7
inactive_border_color #010103
bell_border_color     #77637F

color0      #010104
color1		#77637F
color2		#5F638D
color3		#597185
color4		#4B747F
color5		#7B527C
color6		#536E8D
color7		#6E90BC
color8		#41628C
color9		#77637F
color10		#5F638D
color11		#597185
color12		#4B747F
color13		#7B527C
color14		#536E8D
color15		#AEBFD5