return {
    background = "rgba({{background | strip}}ff)",
    foreground = "rgba({{foreground | strip}}ff)",
    color0     = "rgba({{color0 | strip}}ff)",
    color1     = "rgba({{color1 | strip}}ff)",
    color2     = "rgba({{color2 | strip}}ff)",
    color3     = "rgba({{color3 | strip}}ff)",
    color4     = "rgba({{color4 | strip}}ff)",
    color5     = "rgba({{color5 | strip}}ff)",
    color6     = "rgba({{color6 | strip}}ff)",
    color7     = "rgba({{color7 | strip}}ff)",
    color8     = "rgba({{color8 | strip}}ff)",
    color9     = "rgba({{color9 | strip}}ff)",
    color10    = "rgba({{color10 | strip}}ff)",
    color11    = "rgba({{color11 | strip}}ff)",
    color12    = "rgba({{color12 | strip}}ff)",
    color13    = "rgba({{color13 | strip}}ff)",
    color14    = "rgba({{color14 | strip}}ff)",
    color15    = "rgba({{color15 | strip}}ff)",
}
