# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(030001)
$foreground = rgb(98D2A8)
$color0 = rgb(030001)
$color1 = rgb(488453)
$color2 = rgb(9A6F38)
$color3 = rgb(197CBF)
$color4 = rgb(6E8337)
$color5 = rgb(AA631F)
$color6 = rgb(528863)
$color7 = rgb(87C097)
$color8 = rgb(4E845F)
$color9 = rgb(488453)
$color10 = rgb(9A6F38)
$color11 = rgb(197CBF)
$color12 = rgb(6E8337)
$color13 = rgb(AA631F)
$color14 = rgb(528863)
$color15 = rgb(BAD7C2)
