# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010103)
$foreground = rgb(DEAAD4)
$color0 = rgb(010104)
$color1 = rgb(A16C7C)
$color2 = rgb(6476A6)
$color3 = rgb(9F6A53)
$color4 = rgb(9F63B0)
$color5 = rgb(A46089)
$color6 = rgb(966E90)
$color7 = rgb(C997C0)
$color8 = rgb(8D6086)
$color9 = rgb(A16C7C)
$color10 = rgb(6476A6)
$color11 = rgb(9F6A53)
$color12 = rgb(9F63B0)
$color13 = rgb(A46089)
$color14 = rgb(966E90)
$color15 = rgb(DCC2D7)
