# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000102)
$foreground = rgb(ACA16E)
$color0 = rgb(010102)
$color1 = rgb(4A4F51)
$color2 = rgb(4D504B)
$color3 = rgb(4B5545)
$color4 = rgb(555846)
$color5 = rgb(525959)
$color6 = rgb(6A6345)
$color7 = rgb(908656)
$color8 = rgb(655B30)
$color9 = rgb(4A4F51)
$color10 = rgb(4D504B)
$color11 = rgb(4B5545)
$color12 = rgb(555846)
$color13 = rgb(525959)
$color14 = rgb(6A6345)
$color15 = rgb(BFBAA2)
