/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragmfact.h"
#include "focusmaster.h"
#include "fullscreen.h"
#include "movestack.h"
#include "nametag.h"
#include "pertag.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_fibonacci.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

