local home = os.getenv("HOME")
local scriptsDir = home .. "/.config/hypr/scripts"
local userScriptsDir = home .. "/.config/hypr/UserScripts"

hl.on("hyprland.start", function()
    hl.exec_cmd("awww query || awww-daemon")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("thunar --daemon")
    hl.exec_cmd("nvim --headless +qa")
    hl.exec_cmd("kdeconnect-indicator &")
    hl.exec_cmd("iio-hyprland")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("swaync &")
    hl.exec_cmd("ags &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("hypridle &")
    hl.exec_cmd("pypr &")
    hl.exec_cmd("hyprpm reload -n &")
end)
