#!/bin/sh

case "$(echo -e "dwm\ndmenu\ndwmblocks\nslock\nst\nsxiv\nneofetch\ndunst\npicom" | dmenu -i -p "Edit Configuration of: ")" in 
	dwm)
		exec $TERM $EDITOR $HOME/dotfiles/.config/suckless/dwm/config.def.h
		;;
esac
