#!/usr/bin/env bash
#
# Script name: dm-currencies
# Description: Convert prices between currencies using https://rate.sx
# Dependencies: dmenu and curl
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: ifrendas

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # If $currency_method is not set to manual, get currencies dynamically
  if [[ "${currency_method:-auto}" != "manual" ]]; then
    mapfile -t data < <(curl -Ss rate.sx/:currencies)
    data+=("USD United States dollar")
    for ((i=0; i < ${#data[@]}; ++i)); do
      currencies[$(echo "${data[$i]}" | awk '{print substr($0, index($0, $2))}')]="$(echo "${data[$i]}" | cut -d' ' -f1)"
      done
    unset data
  fi

  # If $currency_names is not codes use currency names, else use currency codes
  if [[ "${currency_names:-names}" != "codes" ]]; then
    from_name=$(printf '%s\n' "${!currencies[@]}" | sort | ${DMENU} 'Convert from:') "$@" || exit 1
    to_name=$(printf '%s\n' "${!currencies[@]}" | sort | ${DMENU} 'Convert to:') "$@" || exit 1
    from_code=${currencies[$from_name]}
    to_code=${currencies[$to_name]}
  else
    from_name=$(printf '%s\n' "${currencies[@]}" | sort | ${DMENU} 'Convert from:') "$@" || exit 1
    to_name=$(printf '%s\n' "${currencies[@]}" | sort | ${DMENU} 'Convert to:') "$@" || exit 1
    from_code=${from_name}
    to_code=${to_name}
  fi

  # Get amount and convert it
  amount=$(echo "" | ${DMENU} "Amount (${from_code} -> ${to_code}):")
  converted=$(curl -Ss "https://${to_code}.rate.sx/${amount}${from_code}")

  # Copy amount to clipboard and send notification
  echo "$converted" | cp2cb
  notify-send "Converted amount (in clipboard)" "$converted $to_code"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
