#!/usr/bin/env bash
#
# Script name: dm-dictionary
# Description: uses the translate package as a dictionary
# Dependencies: translate-shell, didyoumean
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Francesco Prem Solidoro

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.

set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {

WORD="$(${DMENU} "Search:")"
TESTWORD="$(dym -c -n=1 "$WORD")"

if [ "$WORD" != "$TESTWORD" ]; then
	KEYWORD=$(dym -c "$WORD" | ${DMENU} "was $WORD a misspelling?(select/no)")
	if [ "$KEYWORD" = "no" ] || [ "$KEYWORD" = "n" ]; then
		KEYWORD="$WORD"
	fi
else
	KEYWORD="$WORD"
fi

if ! [ "${KEYWORD}" ]; then
	printf 'No word inserted\n' >&2
	exit 0
fi
$DMTERM trans -v -d "$WORD"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
