#!/usr/bin/env bash

# Script name: dm-ip
# Description: Get IP from interface (or external)
# Dependencies: dmenu, dig, ip, jq
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Simon Ingelsson

set -euo pipefail
_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  declare -A _ips

  _external=$(dig +short myip.opendns.com @resolver1.opendns.com)
  _ips[external]="${_external}"

  for _iface in $(ip -4 -j addr | jq -r '.[] |{ name: .ifname, ip: .addr_info[].local} | join(":")') ; do
    _ips[${_iface%:*}]="${_iface##*:}"
  done

  selected="$(printf '%s\n' "${!_ips[@]}" | ${DMENU} "ips:" "$@")"
  [ -z "${selected}" ] && exit 1
  echo "${_ips["${selected}"]}" | cp2cb 
  notify-send "IP (in clipboard)" " ${selected}: ${_ips["${selected}"]}"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
