#!/usr/bin/env bash
#
# Script name: dm-note
# Description: Store multiple one-line texts or codes and copy one of them when needed.
# Dependencies: dmenu, xclip
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Fawzakin

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd "$(dirname "$(readlink "${BASH_SOURCE[0]}" || echo ".")")" && pwd)"
if [[  -f "${_path}/_dm-helper.sh" ]]; then
  # shellcheck disable=SC1090,SC1091
  source "${_path}/_dm-helper.sh"
else
  # shellcheck disable=SC1090
  echo "No helper-script found"
fi

# script will not hit this if there is no config-file to load
# shellcheck disable=SC1090
source "$(get_config)"

main() {
  # Picking our options.
  choice=$(printf 'Copy note\nNew note\nDelete note\nQuit' | ${DMENU} 'Notes:' "$@")

  # Choose what we should do with our choice.
  case "$choice" in
    'Copy note')
      # shellcheck disable=SC2154
      note_pick=$(${DMENU} 'Copy:' "$@" < "${note_dir}")
      [ -n "${note_pick}" ] && echo "${note_pick}" | cp2cb && notify-send -u normal "Note copied" "${note_pick}"
      ;;
    'New note')
      note_new=$(echo "" | ${DMENU} 'Enter new note:' "$@")
      # Making sure the input is not empty and not already exist in note_dir.
      # The sed command should prevent grep from taking certain characters as a regex input.
      [ -n "$note_new" ] && ! grep -q "^$(echo "${note_new}" | sed -e 's/\[/\\[/g;s/\]/\\]/g')\$" "${note_dir}" &&
      echo "${note_new}" >> "${note_dir}" && notify-send -u normal "Note created" "${note_new}"
      ;;
    'Delete note')
      note_del=$(${DMENU} 'Delete:' "$@" < "${note_dir}")
      # grep should always returns 0 regardless what happens.
      grep -v "^$(echo "${note_del}" | sed -e 's/\[/\\[/g;s/\]/\\]/g')\$" "${note_dir}" > "/tmp/dmnote" || true
      [ -n "${note_del}" ] && cp -f "/tmp/dmnote" "${note_dir}" && notify-send -u normal "Note deleted" "${note_del}"
      ;;
    'Quit')
      echo "Program terminated." && exit 0
      ;;
    *)
      exit 0
    ;;
  esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
