#!/bin/sh
pass=$(dmenu -P -p "Enter BitWarden Master Password: ")
export BW_SESSION=$(bw unlock --raw "$pass")
filepath="$HOME/bwtmp"
#(bw list items --pretty | sed '/object/d'| sed '/organizationId/d'| sed '/folderId/d'| sed '/type/d'| sed '/reprompt/d'| sed '/password/d') > $filepath
if [ ! -e "$filepath" ]
then
    echo "file not exist"
    (bw list items --pretty | sed '/object/d' | sed '/organizationId/d' | sed '/folderId/d' | sed '/type/d' | sed '/http/d' | sed '/match/d' | sed '/reprompt/d' | sed '/notes/d' | sed '/favorite/d' | sed '/password/d' | sed 's/\"totp\": null\,/\"totp\": null/g' | sed '/favorite/d' | sed '/collectionIds/d' | sed '/revisionDate/d' | sed '/creationDate/d') > $filepath
fi
#(bw list items --pretty | sed '/object/d' | sed '/organizationId/d' | sed '/folderId/d' | sed '/type/d' | sed '/reprompt/d' | sed '/notes/d' | sed '/http/d' | sed '/match/d' | sed '/favorite/d' | sed '/password/d' | sed 's/\"totp\": null\,/\"totp\": null/g' ) > $filepath
n=$(jq '.[].name' $filepath | wc -l)
details=""
endline="\n"
for (( i=0; i < $n; i++ )) 
do
    details+="$(printf "%s - URL:%s - Username:%s\n" "$i" "$(jq ".[$i].name" $filepath)" "$(jq ".[$i].login.username" $filepath)" | sed 's/[\",]//g')$(echo $endline)"
done
choice=$(echo -e $details | dmenu -i -l 10)
id=$(jq ".[$(echo $choice | awk '{print $1}')].id" $filepath | sed 's/[\",]//g')
pass=$(bw get password $id)
echo $pass | xclip -selection clipboard
#shred -uz $filepath
bw lock --quiet
