#!/bin/sh

case "$(echo -e "Shutdown\nReboot\nHibernate\nLogout\nSuspend\nLock" | dmenu -p "POWER MENU:")" in
	Shutdown)
		case "$(echo -e "Yes\nNo" | dmenu -p "Are you sure?")" in
			Yes) shutdown now ;;
	  		No) exit ;;
	  	esac
	  	;;
	Reboot)
		case "$(echo -e "Yes\nNo" | dmenu -p "Are you sure?")" in
			Yes) reboot ;;
			No) exit ;;
		esac
		;;
	Hibernate)
		case "$(echo -e "Yes\nNo" | dmenu -p "Are you sure?")" in
			Yes) systemctl hibernate ;;
			No) exit ;;
		esac
		;;
	Logout)
		case "$(echo -e "Yes\nNo" | dmenu -p "Are you sure?")" in
			Yes) kill -9 -1 ;;
			No) exit ;;
		esac
		;;
	Suspend)
		systemctl suspend
		;;
	Lock) 
		slock 
		;;
esac
