#!/bin/sh
bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -i -l 5 -p "Select Wifi  :" | awk '{ print $2 }')
pass=$(echo "" | dmenu -P -p "Enter Password  :")
[ -n "$pass" ] && (nmcli device wifi connect "$bssid" password "$pass" || nmcli device wifi connect "$bssid")
sleep 10
if ping -q -c 2 -W 2 google.com >/dev/null; then
	notify-send "Your internet is working :)"
else
	notify-send "Your internet is not working :("
fi
exit
