#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.

#case $BLOCK_BUTTON in
#	1) "$TERMINAL" -e nmtui; pkill -RTMIN+4 dwmblocks ;;
#	3) notify-send "🌐 Internet module" "\- Click to connect
#📡: no wifi connection
#📶: wifi connection with quality
#❎: no ethernet
#🌐: ethernet working
#" ;;
#	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
#esac

case "$(cat /sys/class/net/e*/operstate 2>/dev/null)" in
	down) case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
			down) printf "%s\n" " Not Connected" ;;
			up) printf "%s%s\n" "$(awk '/^\s*w/ { print "", int($3 * 100 / 70) "% " }' /proc/net/wireless)" "$(iw dev wlo1 link | grep -i ssid | awk '{print $2}')" ;;
	      esac ;;
	up) printf "%s\n" " Ethernet Connected" ;;
esac

